export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GOOGLE_SIGNIN_START = 'GOOGLE_SIGNIN_START';
export const EMAIL_SIGNIN_START = 'EMAIL_SIGNIN_START';
export const SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'GOOGLE_SIGNIN_FAILURE';
